-- Insert sample promotional images for testing
INSERT INTO promotional_images (
  title,
  subtitle,
  button_text,
  brand_name,
  image_url,
  image_alt,
  gradient_from,
  gradient_to,
  is_active,
  display_order,
  auto_rotate_duration,
  action_type,
  action_url,
  action_target,
  target_audience,
  click_count,
  view_count
) VALUES 
(
  'Earn More with Every Job',
  'Complete tasks and boost your income',
  'View Jobs',
  'Nakoda Partner',
  'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=400&fit=crop&crop=center',
  'Professional worker completing tasks',
  'blue-600',
  'indigo-600',
  true,
  1,
  5000,
  'button',
  '/partner/new-task',
  '_self',
  'all',
  0,
  0
),
(
  'Flexible Working Hours',
  'Work when it suits you best',
  'Get Started',
  'Nakoda Partner',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=400&fit=crop&crop=center',
  'Flexible work schedule concept',
  'green-600',
  'emerald-600',
  true,
  2,
  5000,
  'button',
  '/partner/new-task',
  '_self',
  'all',
  0,
  0
),
(
  'Professional Support',
  '24/7 assistance for all partners',
  'Learn More',
  'Nakoda Partner',
  'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop&crop=center',
  'Customer support team',
  'purple-600',
  'violet-600',
  true,
  3,
  5000,
  'button',
  '/partner/support',
  '_self',
  'all',
  0,
  0
);
