export interface Database {
  public: {
    Tables: {
      admin_users: {
        Row: {
          id: number;
          name: string;
          email: string;
          phone: string;
          role: string;
          status: 'Active' | 'Inactive';
          access_level: string;
          last_login: string;
          permissions: string[];
          avatar: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          name: string;
          email: string;
          phone: string;
          role: string;
          status?: 'Active' | 'Inactive';
          access_level: string;
          last_login?: string;
          permissions: string[];
          avatar: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          email?: string;
          phone?: string;
          role?: 'Active' | 'Inactive';
          access_level?: string;
          last_login?: string;
          permissions?: string[];
          avatar?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          bitrix24_id: string;
          title: string;
          mode: string | null;
          package: string | null;
          partner: string | null; // New field for partner
          order_number: string | null;
          mobile_number: string | null;
          order_date: string | null;
          order_time: string | null;
          customer_name: string | null;
          address: string | null;
          city: string | null;
          pin_code: string | null;
          service_type: string | null;
          specification: string | null;
          stage_id: string | null;
          stage_semantic_id: string | null;
          status: string;
          currency: string;
          amount: string;
          lead_id: string | null;
          contact_id: string | null;
          company_id: string | null;
          assigned_by_id: string | null;
          created_by_id: string | null;
          begin_date: string | null;
          close_date: string | null;
          date_created: string | null;
          date_modified: string | null;
          is_closed: boolean;
          is_new: boolean;
          comments: string | null;
          additional_info: string | null;
          location_id: string | null;
          category_id: string | null;
          source_id: string | null;
          source_description: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          last_activity_time: string | null;
          last_activity_by: string | null;
          last_communication_time: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          bitrix24_id: string;
          title: string;
          mode?: string | null;
          package?: string | null;
          partner?: string | null; // New field for partner
          order_number?: string | null;
          mobile_number?: string | null;
          order_date?: string | null;
          order_time?: string | null;
          customer_name?: string | null;
          address?: string | null;
          city?: string | null;
          pin_code?: string | null;
          service_type?: string | null;
          specification?: string | null;
          stage_id?: string | null;
          stage_semantic_id?: string | null;
          status?: string;
          currency?: string;
          amount?: string;
          lead_id?: string | null;
          contact_id?: string | null;
          company_id?: string | null;
          assigned_by_id?: string | null;
          created_by_id?: string | null;
          begin_date?: string | null;
          close_date?: string | null;
          date_created?: string | null;
          date_modified?: string | null;
          is_closed?: boolean;
          is_new?: boolean;
          comments?: string | null;
          additional_info?: string | null;
          location_id?: string | null;
          category_id?: string | null;
          source_id?: string | null;
          source_description?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          last_activity_time?: string | null;
          last_activity_by?: string | null;
          last_communication_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bitrix24_id?: string;
          title?: string;
          mode?: string | null;
          package?: string | null;
          partner?: string | null; // New field for partner
          order_number?: string | null;
          mobile_number?: string | null;
          order_date?: string | null;
          order_time?: string | null;
          customer_name?: string | null;
          address?: string | null;
          city?: string | null;
          pin_code?: string | null;
          service_type?: string | null;
          specification?: string | null;
          stage_id?: string | null;
          stage_semantic_id?: string | null;
          status?: string;
          currency?: string;
          amount?: string;
          lead_id?: string | null;
          contact_id?: string | null;
          company_id?: string | null;
          assigned_by_id?: string | null;
          created_by_id?: string | null;
          begin_date?: string | null;
          close_date?: string | null;
          date_created?: string | null;
          date_modified?: string | null;
          is_closed?: boolean;
          is_new?: boolean;
          comments?: string | null;
          additional_info?: string | null;
          location_id?: string | null;
          category_id?: string | null;
          source_id?: string | null;
          source_description?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          last_activity_time?: string | null;
          last_activity_by?: string | null;
          last_communication_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
