import { OngoingTask } from './types';

export const sampleOngoingTasks: OngoingTask[] = [
  {
    id: '1',
    title: 'Deep Cleaning Service',
    customerName: 'Sarah Johnson',
    location: 'Andheri West, Mumbai',
    amount: 2500,
    duration: '3-4 hours',
    serviceType: 'Cleaning',
    orderNumber: 'NUS87638',
    orderDate: '2025-01-09',
    serviceDate: '2025-01-12',
    serviceTime: '09:00',
    status: 'in-progress',
    startTime: '09:15',
    estimatedEndTime: '12:30',
    actualStartTime: '09:15',
    currentPhase: 'Kitchen Cleaning',
    notes: 'Customer requested extra attention to kitchen grease removal',
    photos: ['kitchen-before.jpg', 'kitchen-progress.jpg'],
    customerPhone: '+91 98765 43210',
    customerAddress: 'Flat 502, Building A, Sunshine Apartments, Andheri West',
    advanceAmount: 1000,
    balanceAmount: 1500,
    commissionAmount: 625
  },
  {
    id: '2',
    title: 'Plumbing Repair',
    customerName: 'Rajesh Kumar',
    location: 'Bandra East, Mumbai',
    amount: 1800,
    duration: '2-3 hours',
    serviceType: 'Plumbing',
    orderNumber: 'NUS87639',
    orderDate: '2025-01-09',
    serviceDate: '2025-01-12',
    serviceTime: '10:00',
    status: 'in-progress',
    startTime: '10:05',
    estimatedEndTime: '12:30',
    actualStartTime: '10:05',
    currentPhase: 'Assessment & Diagnosis',
    notes: 'Found additional leak in bathroom pipe',
    photos: ['leak-assessment.jpg'],
    customerPhone: '+91 98765 43211',
    customerAddress: 'Flat 301, Building B, Green Valley, Bandra East',
    advanceAmount: 800,
    balanceAmount: 1000,
    commissionAmount: 360
  },
  {
    id: '3',
    title: 'Electrical Installation',
    customerName: 'Priya Sharma',
    location: 'Juhu, Mumbai',
    amount: 3200,
    duration: '4-5 hours',
    serviceType: 'Electrical',
    orderNumber: 'NUS87640',
    orderDate: '2025-01-09',
    serviceDate: '2025-01-12',
    serviceTime: '11:00',
    status: 'in-progress',
    startTime: '11:10',
    estimatedEndTime: '15:30',
    actualStartTime: '11:10',
    currentPhase: 'Ceiling Fan Installation',
    notes: 'Paused due to missing ceiling fan bracket - customer to provide',
    photos: ['fan-installation.jpg'],
    customerPhone: '+91 98765 43212',
    customerAddress: 'Villa 15, Beach Road, Juhu',
    advanceAmount: 1500,
    balanceAmount: 1700,
    commissionAmount: 960
  },
  {
    id: '4',
    title: 'Carpentry Work',
    customerName: 'Amit Patel',
    location: 'Powai, Mumbai',
    amount: 2200,
    duration: '3-4 hours',
    serviceType: 'Carpentry',
    orderNumber: 'NUS87641',
    orderDate: '2025-01-09',
    serviceDate: '2025-01-12',
    serviceTime: '14:00',
    status: 'completed',
    startTime: '14:05',
    estimatedEndTime: '17:30',
    actualStartTime: '14:05',
    currentPhase: 'Completed',
    notes: 'All furniture assembled successfully, customer satisfied',
    photos: ['furniture-complete.jpg', 'cabinet-fixed.jpg'],
    customerPhone: '+91 98765 43213',
    customerAddress: 'Apartment 1201, Hiranandani Gardens, Powai',
    advanceAmount: 1000,
    balanceAmount: 1200,
    commissionAmount: 484
  }
];
